# Sample Network Configuration
# This configuration creates a basic drone network with multiple server types

# Drone network configuration
# PDR (Packet Drop Rate) values between 0.0 and 1.0

[[drone]]
id = 1
connected_node_ids = [2, 3]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [1, 4, 5]
pdr = 0.1

[[drone]]
id = 3
connected_node_ids = [1, 6]
pdr = 0.02

[[drone]]
id = 4
connected_node_ids = [2, 7, 8]
pdr = 0.08

[[drone]]
id = 5
connected_node_ids = [2, 9]
pdr = 0.03

[[drone]]
id = 6
connected_node_ids = [3, 10]
pdr = 0.06

[[drone]]
id = 7
connected_node_ids = [4, 11]
pdr = 0.04

[[drone]]
id = 8
connected_node_ids = [4, 12]
pdr = 0.07

[[drone]]
id = 9
connected_node_ids = [5, 13]
pdr = 0.02

[[drone]]
id = 10
connected_node_ids = [6, 14]
pdr = 0.09

[[drone]]
id = 11
connected_node_ids = [7, 15]
pdr = 0.05

[[drone]]
id = 12
connected_node_ids = [8, 15]
pdr = 0.03

[[drone]]
id = 13
connected_node_ids = [9, 15]
pdr = 0.08

[[drone]]
id = 14
connected_node_ids = [10, 15]
pdr = 0.01

[[drone]]
id = 15
connected_node_ids = [11, 12, 13, 14]
pdr = 0.04

# Client configuration
# Each client connects to at most 2 drones

[[client]]
id = 100
connected_drone_ids = [1, 3]

[[client]]
id = 101
connected_drone_ids = [5]

[[client]]
id = 102
connected_drone_ids = [7, 9]

# Server configuration (from the config file)
# Each server connects to at least 2 drones

[[server]]
id = 200
connected_drone_ids = [2, 4, 6]

[[server]]
id = 201
connected_drone_ids = [8, 10]

[[server]]
id = 202
connected_drone_ids = [11, 13, 15]