export global Palette {
    in property <color> bg           : #16181a;
    in property <color> bg_alt       : #1e2124;
    in property <color> bg_highlight : #3c4048;
    in property <color> blue         : #5ea1ff;
    in property <color> cyan         : #5ef1ff;
    in property <color> fg           : #ffffff;
    in property <color> green        : #5eff6c;
    in property <color> grey         : #7b8496;
    in property <color> magenta      : #ff5ef1;
    in property <color> orange       : #ffbd5e;
    in property <color> pink         : #ff5ea0;
    in property <color> purple       : #bd5eff;
    in property <color> red          : #ff6e5e;
    in property <color> yellow       : #f1ff5e;
}
