# Subnet with triangles and a square
#1-2---4-5---8-9
# V    |X|    V
# 3----6-7----10

# Left triangle
[[drone]]
id = 1
connected_node_ids = [2, 3, 11]
pdr = 0

[[drone]]
id = 2
connected_node_ids = [1, 3, 4]
pdr = 0

[[drone]]
id = 3
connected_node_ids = [1, 2, 6]
pdr = 0

# Square
[[drone]]
id = 4
connected_node_ids = [2, 5, 6, 7]
pdr = 0

[[drone]]
id = 5
connected_node_ids = [4, 6, 7, 8]
pdr = 0

[[drone]]
id = 6
connected_node_ids = [3, 4, 5, 7]
pdr = 0

[[drone]]
id = 7
connected_node_ids = [4, 5, 6, 10]
pdr = 0

# Right triangle
[[drone]]
id = 8
connected_node_ids = [5, 9, 10]
pdr = 0

[[drone]]
id = 9
connected_node_ids = [8, 10, 12]
pdr = 0

[[drone]]
id = 10
connected_node_ids = [7, 8, 9, 12]
pdr = 0

[[client]]
id = 11
connected_drone_ids = [1]

[[server]]
id = 12
connected_drone_ids = [9, 10]