[[drone]]
id = 1
connected_node_ids = [2, 4, 5, 6, 9]
pdr = 0

[[drone]]
id = 9
connected_node_ids = [1, 3, 4, 5, 6]
pdr = 0

[[client]]
id = 2
connected_drone_ids = [1]

[[client]]
id = 3
connected_drone_ids = [9]

[[server]]
id = 4
connected_drone_ids = [1, 9]

[[server]]
id = 5
connected_drone_ids = [1, 9]

[[server]]
id = 6
connected_drone_ids = [1, 9]